# Generated by Django 4.1 on 2022-08-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTeamMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admin',
            field=models.BooleanField(blank=True),
        ),
    ]
