# Generated by Django 4.1 on 2022-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageTeamMembers', '0006_alter_member_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adminView',
            field=models.CharField(default='(admin)', max_length=7),
            preserve_default=False,
        ),
    ]
